import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { UserContextProvider } from "@/contexts/user-context";

import { userSession } from "@/servers/user";
import LayoutMain from "@/components/home-components/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await userSession();
  return (
    <html lang="en">
      <UserContextProvider user={response?.success ? response.data : null}>
        <LayoutMain>{children}</LayoutMain>
      </UserContextProvider>
    </html>
  );
}
